name: Publish
on:
  release:
    types: [ released, prereleased ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    steps:
      # setup
      - name: Check out code
        uses: actions/checkout@v4
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # publish
      - run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache -PmavenCentralUsername=${{secrets.OSSRH_USERNAME}} -PmavenCentralPassword=${{secrets.OSSRH_PASSWORD}} -PsigningInMemoryKeyId=${{secrets.OSSRH_GPG_SECRET_KEY_ID}} -PsigningInMemoryPassword=${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}}
